### ISSUE TITLE
Can't scrape all components

### ISSUE THREAD

**Issue by elie222** [pointblankdev/tailwindui-storybook#1]
Get this error when running:

```
[INFO] fetching sections..
[INFO] 64 sections found (409 components)
[INFO] fetching react components: Hero Sections (9 components)
[ERROR] getComponent failed: Hero Sections page.evaluate: Evaluation failed: TypeError: Cannot read property 'click' of null
    at eval (eval at evaluate (:303:29), <anonymous>:3:41)
    at NodeList.forEach (<anonymous>)
    at eval (eval at evaluate (:303:29), <anonymous>:2:60)
    at UtilityScript.evaluate (<anonymous>:305:22)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```

**Comment by elie222** [comment]
Ah, just realised it continues scraping even after the error.

**Comment by elie222** [comment]
Ah, never completed :( just quit midway, some other crash

**Comment by wzulfikar** [comment]
Thanks for reporting! Seems like the some sections weren’t fully loaded when the event is triggered. I’ll try to check it.

**Comment by wzulfikar** [comment]
Hey @elie222, I adjusted the script to stop on error in case it helps. 

Unfortunately, I couldn't reproduce your error. On my end, I'm testing it with macos chromium and things are okay. FWIW, depending on your connection, it may take ~3 minutes to finish. 

Here's 5x speed of the process (acquiring the json file):

https://user-images.githubusercontent.com/7823011/115062612-1f202380-9f1d-11eb-88a9-4abb5d7c17d3.mp4

Once you get the json file, you can run `node tailwind-storybook.js ./output/tailwindui.react.json react`:

https://user-images.githubusercontent.com/7823011/115063736-89859380-9f1e-11eb-8582-239b8e7c495f.mp4

**Comment by wzulfikar** [comment]
Hey @elie222, I found the issue. It seems that you have not passed a correct login credential. I pushed an update to make the error clear if it's login error. 

Feel free to reopen if you still have an issue.

**Comment by elie222** [comment]
Hmmm... That does seem to be the issue. Although still not able to get it working. It may be because the password contains special characters. I'll try debug it myself later. When I enter the info manually in the Chromium/Playwright browser it works.

**Comment by elie222** [comment]
Yes, the issue is that password is:
`AAA$XXXX@BBB`
And when console logging in the script I see:
`AAA@BBB` printed instead.

Will look into further later.

**Comment by wzulfikar** [comment]
Ah yeah, that `$XXXX` is treated as shell variable and it’s likely that you don’t have such variable in your shell and thus, it was translated to empty string, making it `AAA@BBB`.

Yup, definitely you can just add your email/pass in the script itself. Anyway, glad it works!

**Comment by wzulfikar** [comment]
FWIW, you can wrap the password in single quote to prevent variable expansion:

`email=someemail@example.com password='AAA$XXXX@BBB' node ...`

**Comment by elie222** [comment]
Thanks. Tried double quotes before 😅

Best,
Eliezer
